using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Reflection;
using System.Text;
using tik4net.Objects;

namespace tik4net.unittests.Objects
{
    /// <summary>
    /// Builds the entity catalog table from the <c>[TikEntity]</c> attributes themselves, so the wiki's
    /// <i>Entity reference</i> page cannot quietly fall behind the code.
    /// </summary>
    /// <remarks>
    /// A hand-maintained list of 169 entities drifts on the first one somebody adds, and a reader has no
    /// way to tell a stale row from a current one. So the table is generated and
    /// <see cref="EntityCatalogTests"/> fails when the tracked copy no longer matches.
    /// <para>
    /// Only what the attributes actually say is generated. The prose a reader needs but reflection cannot
    /// know — why the four <c>*-server</c> singletons refuse <c>=detail=</c>, that wireless and wifi are
    /// two drivers — is hand-written around the generated block on the wiki page.
    /// </para>
    /// </remarks>
    internal static class EntityCatalogMarkdown
    {
        /// <summary>Marker footnote numbers, in the order the legend lists them.</summary>
        private const int MarkerSingleton = 1;
        private const int MarkerReadOnly = 2;
        private const int MarkerOrdered = 3;
        private const int MarkerCliStats = 4;
        private const int MarkerHelpers = 5;

        /// <summary>
        /// Every mapped entity type, i.e. every public type in tik4net.objects carrying
        /// <c>[TikEntity]</c>.
        /// </summary>
        internal static IEnumerable<Type> EntityTypes()
            => typeof(TikEntityAttribute).Assembly.GetTypes()
                .Where(t => t.IsClass && t.IsPublic)
                .Where(t => t.GetCustomAttribute<TikEntityAttribute>(false) != null);

        /// <summary>
        /// Entity type name -&gt; the <c>*ConnectionExtensions</c> class that carries its non-CRUD verbs.
        /// The convention is the class name: <c>ToolPingConnectionExtensions</c> serves <c>ToolPing</c>.
        /// </summary>
        /// <remarks>
        /// <see cref="EntityCatalogTests.EveryHelperClassNamesItsEntity"/> holds the convention: an
        /// extension class that resolves to no entity is a naming mistake, not a reason to loosen this.
        /// The generic <c>Tik*</c> extension classes are the API surface itself, not per-entity helpers.
        /// </remarks>
        internal static IDictionary<string, Type> HelperClasses()
        {
            var result = new Dictionary<string, Type>(StringComparer.Ordinal);
            foreach (Type t in typeof(TikEntityAttribute).Assembly.GetTypes()
                         .Where(t => t.IsClass && t.IsPublic && t.IsAbstract && t.IsSealed)   // static
                         .Where(t => t.Name.EndsWith("ConnectionExtensions", StringComparison.Ordinal))
                         .Where(t => !t.Name.StartsWith("Tik", StringComparison.Ordinal)))
            {
                string entityName = t.Name.Substring(0, t.Name.Length - "ConnectionExtensions".Length);
                result[entityName] = t;
            }
            return result;
        }

        /// <summary>Renders the whole catalog as the markdown block the wiki page embeds.</summary>
        internal static string Build()
        {
            var helpers = HelperClasses();
            var rows = EntityTypes()
                .Select(t => new
                {
                    Type = t,
                    Attr = t.GetCustomAttribute<TikEntityAttribute>(false)!,
                })
                .Select(x => new
                {
                    x.Type,
                    Path = x.Attr.EntityPath,
                    Root = RootOf(x.Attr.EntityPath),
                    Markers = MarkersOf(x.Attr, x.Type, helpers),
                })
                .OrderBy(x => x.Root, StringComparer.Ordinal)
                .ThenBy(x => x.Path, StringComparer.Ordinal)
                .ToList();

            var sb = new StringBuilder();
            sb.AppendLine("<!-- GENERATED by tik4net.unittests EntityCatalogMarkdown - do not edit by hand. -->");
            sb.AppendLine();
            sb.AppendLine(string.Format(CultureInfo.InvariantCulture,
                "**{0} entities** are mapped. Markers are explained in the legend above.", rows.Count));

            foreach (var group in rows.GroupBy(r => r.Root).OrderBy(g => g.Key, StringComparer.Ordinal))
            {
                string ns = CommonNamespace(group.Select(g => g.Type));
                sb.AppendLine();
                sb.AppendLine("### " + group.Key);
                sb.AppendLine();
                sb.AppendLine("Namespace `" + ns + "`.");
                sb.AppendLine();
                sb.AppendLine("| RouterOS path | Class | |");
                sb.AppendLine("|---|---|---|");
                foreach (var row in group)
                {
                    sb.AppendLine("| `" + row.Path + "` | `" + row.Type.Name + "` | "
                                  + string.Join(" ", row.Markers.Select(Superscript)) + " |");
                }
            }
            return sb.ToString().Replace("\r\n", "\n");
        }

        /// <summary>The RouterOS top-level menu a path belongs to, e.g. <c>/ip/firewall/filter</c> -&gt; <c>/ip</c>.</summary>
        private static string RootOf(string path)
        {
            string trimmed = path.TrimStart('/');
            int slash = trimmed.IndexOf('/');
            return "/" + (slash < 0 ? trimmed : trimmed.Substring(0, slash));
        }

        private static IList<int> MarkersOf(TikEntityAttribute attr, Type type, IDictionary<string, Type> helpers)
        {
            var markers = new List<int>();
            if (attr.IsSingleton) markers.Add(MarkerSingleton);
            if (attr.IsReadOnly) markers.Add(MarkerReadOnly);
            if (attr.IsOrdered) markers.Add(MarkerOrdered);
            if (attr.IncludeCliStats) markers.Add(MarkerCliStats);
            if (helpers.ContainsKey(type.Name)) markers.Add(MarkerHelpers);
            return markers;
        }

        /// <summary>
        /// The namespace shared by a menu's entities, so the table states it once instead of per row.
        /// Sub-menus map to sub-namespaces, so the shared prefix is the useful answer.
        /// </summary>
        private static string CommonNamespace(IEnumerable<Type> types)
        {
            var namespaces = types.Select(t => (t.Namespace ?? string.Empty).Split('.')).ToList();
            var shared = new List<string>();
            for (int i = 0; ; i++)
            {
                if (namespaces.Any(n => n.Length <= i)) break;
                string part = namespaces[0][i];
                if (namespaces.Any(n => !string.Equals(n[i], part, StringComparison.Ordinal))) break;
                shared.Add(part);
            }
            return string.Join(".", shared);
        }

        private static string Superscript(int n)
        {
            const string digits = "⁰¹²³⁴⁵⁶⁷⁸⁹";
            return n.ToString(CultureInfo.InvariantCulture)
                    .Aggregate(string.Empty, (acc, c) => acc + digits[c - '0']);
        }
    }
}
